import {
  SiPython,
  SiJavascript,
  SiHtml5,
  SiCss,
  SiReact,
  SiDjango,
  SiFlask,
  SiGit,
  SiGithub,
  SiPostgresql,
  SiSqlite,
  SiPandas,
  SiNumpy,
  SiBootstrap,
  SiTensorflow,
  SiPytorch,
  SiScikitlearn,
  SiKeras,
  SiJupyter,
  SiPostman,
  SiFirebase,
  SiMysql,
  SiC,
} from "react-icons/si";

import { FaBrain, FaChartBar, FaCode, FaJava } from "react-icons/fa";

export const skillIcons = {
  Python: SiPython,
  Java: FaJava,
  JavaScript: SiJavascript,
  HTML5: SiHtml5,
  CSS3: SiCss,
  React: SiReact,
  Django: SiDjango,
  Flask: SiFlask,
  Bootstrap: SiBootstrap,
  "REST API": FaCode,
  "Machine Learning": FaBrain,
  "Deep Learning": FaBrain,
  TensorFlow: SiTensorflow,
  PyTorch: SiPytorch,
  "Scikit-learn": SiScikitlearn,
  Keras: SiKeras,
  LLM: FaBrain,
  "C / Basics": SiC,
  Matplotlib: FaChartBar,
  Seaborn: FaChartBar,
  EDA: FaChartBar,
  Streamlit: FaChartBar,
  Git: SiGit,
  GitHub: SiGithub,
  "VS Code": FaCode,
  "Jupyter Notebook": SiJupyter,
  Postman: SiPostman,
  PostgreSQL: SiPostgresql,
  SQLite: SiSqlite,
  Firebase: SiFirebase,
  MySQL: SiMysql,
  Pandas: SiPandas,
  NumPy: SiNumpy,
};